site_name: Working with the Unix Shell
nav:
  - Introduction: index.md
  - Navigation: 01_navigation.md
  - Command History: 02_command_history.md
  - File Operations: 03_file_operations.md
  - Creating Examples: 04_creating_example_files.md
  - Searching for Files: 05_searching_for_files.md
  - Searching in Files: 06_searching_inside_files.md
  - Editing Files: 07_editing_files.md
  - Shell Scripting: 08_shell_scripts.md
  - Putting it together: 09_script_example.md
theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js