site_name: Working with the Unix Shell
nav:
  - Home: index.md
  - Introduction: 01_summary_and_setup.md
  - Navigation: 02_navigation.md
  - Command History: 03_command_history.md
  - File Operations: 04_file_operations.md
  - Creating Examples: 05_creating_example_files.md
  - Searching for Files: 06_searching_for_files.md
  - Searching in Files: 07_searching_inside_files.md
  - Editing Files: 08_editing_files.md
  - Shell Scripting: 09_shell_scripts.md
theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js