site_name: My Docs
nav:
  - Home: index.md
  - Introduction: 01_summary_and_setup.md
  - Navigation: 02_navigation.md
  - Command History: 03_command_history.md
  - File Operations: 04_file_operations.md
  - Searching and Editing: 05_searching_and_editing.md
theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js